name: py310_data_analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - sparqlwrapper
  - pandas
  - ipykernel
  - ipywidgets
  - seaborn
  - plotly
  - ipyleaflet
  - networkx